granja/urls.py
from django.urls import path
from granja import views

app_name = 'granja'

urlpatterns = [
    path('', views.vendas, name='index'), 
    path('dashboard/', views.dashboard, name='dashboard'), 

    path('empresa/<str:arroba>/', views.empresa),

    path('produtos/', views.produtos, name='produtos'),
    path('produto/criar/', views.criar_produto, name='criar_produto'),
    path('produto/<int:id>/editar/', views.editar_produto, name='editar_produto'),
    path('produto/<int:id>/excluir/', views.excluir_produto, name='excluir_produto'),  

    path('vendas/', views.vendas, name='vendas'),
    path('venda/criar/', views.gerar_venda, name='gerar_venda'),
    path('venda/<int:id>/editar/', views.editar_venda, name='editar_venda'),
    path('venda/<int:id>/excluir/', views.excluir_venda, name='excluir_venda'),
    path('excluir/<str:model>/<int:pk>/', views.excluir, name='excluir'),  

    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('', include('granja.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

granja/forms.py
from datetime import date
from django import forms
from .models import Produto, Venda, Cliente
from django.forms.widgets import TextInput, NumberInput, Select, FileInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'telefone', 'endereco', 'meio_de_contato']
        widgets = {
            'nome': TextInput(attrs={'class': 'form-control'}),
            'telefone': TextInput(attrs={'class': 'form-control'}),
            'endereco': TextInput(attrs={'class': 'form-control'}),
            'meio_de_contato': Select(attrs={'class': 'custom-select col-12'}),
        }

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
            'foto',
            'nome', 
            'preco_riscado', 
            'preco',
            'descricao',
            'estoque', 
            'arquivado',
            #'cor', 
        ]
        widgets = {
            'estoque': Select(attrs={
                'class': 'custom-select col-12'
            }),
            'nome': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ovos...'
            }),
            'preco_riscado': NumberInput(attrs={
                'class': 'form-control',
                'value': '20.00'
            }),
            'preco': NumberInput(attrs={
                'class': 'form-control',
                'value': '17.00'
            }),
            'cor': TextInput(attrs={
                'class': 'form-control',
                'value': '#563d7c',
                'type': 'color'
            }),
            'foto': FileInput(attrs={'class': 'form-control-file form-control height-auto'}),
            'descricao': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ovos Caipira...'
            }),
        }

class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = [
            #'vendedor',
            'cliente',
            'produto',
            'quantidade',
            'meio_de_pagamento',
            'desconto',
            #'data_pedido',
            'data_entrega',
        ]
        widgets = {
            'cliente': forms.Select(attrs={'class': 'custom-select col-12'}),
            'produto': forms.Select(attrs={'class': 'custom-select col-12'}),
            'quantidade': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': 1
            }),
            'meio_de_pagamento': forms.Select(attrs={'class': 'custom-select col-12'}),
            'desconto': forms.Select(attrs={'class': 'custom-select col-12'}),
            
            'data_entrega': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance and instance.data_entrega:
            self.initial['data_entrega'] = instance.data_entrega.strftime('%Y-%m-%d')
        if not self.instance.pk:  
            self.fields['data_entrega'].initial = date.today().isoformat()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

granja/views.py
from django.shortcuts import render, redirect, get_object_or_404
from granja.models import Venda, Produto, Estoque, Cliente, Vendedor, AppUser
from granja.forms import ProdutoForm, VendaForm, ClienteForm, UserRegisterForm
from .dashboard import Dashboard
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    return render(request, 'granja/pages/vendas.html', {
        'vendas': Venda.objects.all(),
    })


def dashboard(request):
    today = datetime.today()
    option = None

    if request.method == "GET":
        date_str = request.GET.get('date')
        option = request.GET.get('option')

        if date_str:
            today = datetime.strptime(date_str, '%d-%m-%Y')

    if option == '1':
        dashboard_obj = Dashboard(today)
    elif option == '2':
        last_week = today - timedelta(days=7)
        dashboard_obj = Dashboard(last_week)
    else:
        dashboard_obj = Dashboard(today)

    #today = datetime(2024, 6, 23)
    dashboard = Dashboard(today)

    semana_passada = dashboard.totais_semana_passada
    semana_atual = dashboard.totais_semana_atual
    tamanho_grafico = dashboard.calcular_tamanho_grafico()
    messagem_whatsapp =  dashboard.mensagem

    clientes = dashboard.total_clientes
    lucro = dashboard.total_valor
    formas = dashboard.total_formas
    clientes_semana_passada = dashboard.total_clientes_semana_passada
    lucro_semana_passada = dashboard.total_valor_semana_passada
    formas_semana_passada = dashboard.total_formas_semana_passada

    diferenca_lucro = abs(dashboard.total_valor - dashboard.total_valor_semana_passada)
    porcentagem_aumento = 0

    if lucro == 0 or lucro_semana_passada == 0:
        porcentagem_aumento = 0
    else:
        porcentagem_aumento = (diferenca_lucro / min(lucro_semana_passada, lucro)) * 100


    return render(request, 'granja/pages/dashboard.html', {
        'option': option,
        'clientes': clientes,
        'lucro': lucro,
        'formas': formas,

        'clientes_semana_passada': clientes_semana_passada,
        'lucro_semana_passada': lucro_semana_passada,
        'formas_semana_passada': formas_semana_passada,
        'diferenca_lucro': diferenca_lucro,

        'porcentagem_aumento': porcentagem_aumento,

        'messagem_whatsapp': messagem_whatsapp,

        'semana_atual': semana_atual,
        'semana_passada': semana_passada,
        'tamanho_grafico': tamanho_grafico,

        'DIA_DA_SEMANA_CHOICES': Venda.DIA_DA_SEMANA_CHOICES,
    })


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        data = request.POST
        if form.is_valid():
            role = data.get('role', None)
            user = form.save(commit=False) 
            user.save()
            AppUser.objects.create(user=user, user_type=role)
            #print(form.cleaned_data, data, role)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Conta criada para {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'granja/auth/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, 'Usuário ou senha inválidos')
        else:
            messages.error(request, 'Usuário ou senha inválidos')
    else:
        form = AuthenticationForm()
    return render(request, 'granja/auth/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(dashboard)


def empresa(request, arroba):
    return render(request, 'granja/auth/auth.html')




def produtos(request):
    produtos = Produto.objects.all()

    return render(request, 'granja/pages/products.html', {
        'produtos': produtos,
        'sub_title': 'Produtos'
    })


def criar_produto(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('granja:index')
    else:
        form = ProdutoForm()

    form.fields['estoque'].queryset = Estoque.objects.all()  
    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'sub_title': 'Criar Produto'
        })


def editar_produto(request, id):
    obj = Produto
    editar = [True, obj.__name__.lower(), id]
    produto = get_object_or_404(obj, pk=id)
    

    if request.method == 'POST':
        form = ProdutoForm(request.POST, request.FILES, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('granja:produtos') 
    else:
        form = ProdutoForm(instance=produto)

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'produto': produto,
        'editar': editar,
        'sub_title': 'Editar Produto'
    })


def excluir_produto(request, id):
    try:
        Produto.objects.get(id=id).delete()
    except Exception as e:
        print("Error!")
    return redirect('granja:produtos')


def vendas(request):
    vendas = Venda.objects.all().order_by('-data_entrega')[:20]

    return render(request, 'granja/pages/vendas.html', {
        'vendas': vendas,
        'sub_title': 'Vendas'
    })


def gerar_venda(request):
    if request.method == 'POST':
        form = VendaForm(request.POST, request.FILES)
        form2 = ClienteForm(request.POST, request.FILES)
        if form2.is_valid():
            cliente = form2.cleaned_data
            cliente['nome'] = cliente['nome'].title()
        
            obj = None
            meio_de_contato = cliente['meio_de_contato']            
            list_filter = {
                '1': Cliente.objects.check(nome=cliente['nome'], telefone=cliente['telefone'], meio_de_contato=meio_de_contato),
                '2': Cliente.objects.check(telefone=cliente['telefone'], meio_de_contato=meio_de_contato),
                '3': Cliente.objects.check(nome=cliente['nome'], meio_de_contato=meio_de_contato),
            }

            cliente_id = None
            for key, value in list_filter.items():
                if value:
                    cliente_id = value.id
                    break

            if cliente_id:
                obj = Cliente.objects.get(id=cliente_id)
            else:
                obj = Cliente.objects.create(**cliente)

            if not obj.nome and cliente.get('nome', None) is not None:
                obj.nome = cliente['nome']
            if not obj.nome and cliente.get('nome', None) is not None:
                obj.nome = cliente['nome']
            if not obj.endereco and cliente.get('endereco', None) is not None:
                obj.endereco = cliente['endereco']
            obj.save()

            if form.is_valid():
                venda = form.save(commit=False)
                venda.cliente = obj
                venda.save()
                return redirect('granja:index')        
    else:
        form = VendaForm()
        form2 = ClienteForm()

    #form.fields['cliente'].queryset = Cliente.objects.all()
    form.fields['produto'].queryset = Produto.objects.all()

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'form2': form2,
        'sub_title': 'Gerar Venda'
    })


def editar_venda(request, id):
    obj = Venda
    editar = [True, obj.__name__.lower(), id]
    venda = get_object_or_404(obj, pk=id)

    if request.method == 'POST':
        form = VendaForm(request.POST, request.FILES, instance=venda)
        if form.is_valid():
            form.save()
            return redirect('granja:vendas') 
    else:
        form = VendaForm(instance=venda)

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'venda': venda,
        'editar': editar,
        'sub_title': 'Editar Venda'
    })


def excluir_venda(request, id):
    try:
        Venda.objects.get(id=id).delete()
    except Exception as e:
        print("Error!")
    return redirect('granja:produtos')


def excluir(request, model, pk):
    url_anterior = request.META.get('HTTP_REFERER', '/')
    model_class = {
        'venda': Venda,
        'produto': Produto,
        'cliente': Cliente,
    }.get(model)

    if model_class is None:
        return redirect(url_anterior)

    objeto = get_object_or_404(model_class, pk=pk)
    
    objeto.delete()
    return redirect('granja:index')

granja/templates/granja/pages/admin_form.html
{% extends "granja/base.html" %}
{% load static %}

{% block main_container %}
<style>
	.hidden-field {
		display: none;
	}
</style>

{% include 'granja/partials/sub-header.html' %}

<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form2.non_field_errors }}
	{{ form.non_field_errors }}
	{% if form2 %}
		{% for field in form2 %}
			{% include "forms/field_template.html" %}
		{% endfor %}
	<hr>
	{% endif %}
	{{ form.media }}
	{% for field in form %}
		{% if field.name != 'cliente' %}
			{% include "forms/field_template.html" %}
		{% else %}
			<div class="hidden-field">
				{{ field }}
			</div>
		{% endif %}
	{% endfor %}
	<button type="submit" class="btn btn-outline-primary">{{ sub_title }}</button>
	{% if editar.0 %}
		<a class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmation-modal" type="button"> Excluir </a>
		<div class="col-md-4 col-sm-12 mb-30">
				<div class="modal fade" id="confirmation-modal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">
							<div class="modal-body text-center font-18">
								<h4 class="padding-top-30 mb-30 weight-500">
									Tem certeza que deseja excluir este item?
								</h4>
								<div class="padding-bottom-30 row" style="max-width: 170px; margin: 0 auto">
									<div class="col-6">
										<button type="button" class="btn btn-secondary border-radius-100 btn-block confirmation-btn" data-dismiss="modal">
											<i class="fa fa-times"></i>
										</button>
										NÃO
									</div>
									<div  class="col-6">
										<a href="{% url 'granja:excluir' editar.1 editar.2 %}" type="button" class="btn btn-danger border-radius-100 btn-block confirmation-btn">
											<i class="fa fa-check"></i>
										</a>
										SIM
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endif %}
</form>
{% endblock main_container %}					

granja/templates/granja/pages/admin_form_wizard.html
{% extends "granja/base.html" %}
{% load static %}
{% block main_container %}

<link rel="stylesheet" href="{% static 'granja/css/jquery.steps.css' %}">

<script src="{% static 'granja/scripts/jquery.steps.js' %}"></script>
<script src="{% static 'granja/scripts/steps-setting.js' %}"></script>

<div class="pd-20 card-box mb-30">
    <div class="clearfix">
        <h4 class="text-blue h4">Step wizard</h4>
        <p class="mb-30">jQuery Step wizard</p>
    </div>
    <div class="wizard-content">
        <form class="tab-wizard wizard-circle wizard clearfix" role="application" id="steps-uid-0"><div class="steps clearfix"><ul role="tablist"><li role="tab" class="first current" aria-disabled="false" aria-selected="true"><a id="steps-uid-0-t-0" href="#steps-uid-0-h-0" aria-controls="steps-uid-0-p-0"><span class="current-info audible">current step: </span><span class="step">1</span> Personal Info</a></li><li role="tab" class="done" aria-disabled="false" aria-selected="false"><a id="steps-uid-0-t-1" href="#steps-uid-0-h-1" aria-controls="steps-uid-0-p-1"><span class="step">2</span> Job Status</a></li><li role="tab" class="disabled" aria-disabled="true"><a id="steps-uid-0-t-2" href="#steps-uid-0-h-2" aria-controls="steps-uid-0-p-2"><span class="step">3</span> Interview</a></li><li role="tab" class="disabled last" aria-disabled="true"><a id="steps-uid-0-t-3" href="#steps-uid-0-h-3" aria-controls="steps-uid-0-p-3"><span class="step">4</span> Remark</a></li></ul></div><div class="content clearfix">
            <h5 id="steps-uid-0-h-0" tabindex="-1" class="title current">Personal Info</h5>
            <section id="steps-uid-0-p-0" role="tabpanel" aria-labelledby="steps-uid-0-h-0" class="body current" aria-hidden="false" style="">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>First Name :</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Last Name :</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Email Address :</label>
                            <input type="email" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Phone Number :</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Select City :</label>
                            <select class="custom-select form-control">
                                <option value="">Select City</option>
                                <option value="Amsterdam">India</option>
                                <option value="Berlin">UK</option>
                                <option value="Frankfurt">US</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Date of Birth :</label>
                            <input type="text" class="form-control date-picker" placeholder="Select Date">
                        </div>
                    </div>
                </div>
            </section>
            <!-- Step 2 -->
            <h5 id="steps-uid-0-h-1" tabindex="-1" class="title">Job Status</h5>
            <section id="steps-uid-0-p-1" role="tabpanel" aria-labelledby="steps-uid-0-h-1" class="body" aria-hidden="true" style="display: none;">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Job Title :</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Company Name :</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Job Description :</label>
                            <textarea class="form-control"></textarea>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Step 3 -->
            <h5 id="steps-uid-0-h-2" tabindex="-1" class="title">Interview</h5>
            <section id="steps-uid-0-p-2" role="tabpanel" aria-labelledby="steps-uid-0-h-2" class="body" aria-hidden="true" style="display: none;">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Interview For :</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Interview Type :</label>
                            <select class="form-control">
                                <option>Normal</option>
                                <option>Difficult</option>
                                <option>Hard</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Interview Date :</label>
                            <input type="text" class="form-control date-picker" placeholder="Select Date">
                        </div>
                        <div class="form-group">
                            <label>Interview Time :</label>
                            <input class="form-control time-picker td-input" placeholder="Select time" type="text" readonly="">
                        </div>
                    </div>
                </div>
            </section>
            <!-- Step 4 -->
            <h5 id="steps-uid-0-h-3" tabindex="-1" class="title">Remark</h5>
            <section id="steps-uid-0-p-3" role="tabpanel" aria-labelledby="steps-uid-0-h-3" class="body" aria-hidden="true" style="display: none;">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Behaviour :</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Confidance</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Result</label>
                            <select class="form-control">
                                <option>Select Result</option>
                                <option>Selected</option>
                                <option>Rejected</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Comments</label>
                            <textarea class="form-control"></textarea>
                        </div>
                    </div>
                </div>
            </section>
        </div><div class="actions clearfix"><ul role="menu" aria-label="Pagination"><li class="disabled" aria-disabled="true"><a href="#previous" role="menuitem">Previous</a></li><li aria-hidden="false" aria-disabled="false"><a href="#next" role="menuitem">Next</a></li><li aria-hidden="true" style="display: none;"><a href="#finish" role="menuitem">Submit</a></li></ul></div></form>
    </div>
</div>
{% endblock %}

granja/templates/granja/pages/index4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Vendas</title>
</head>
<body>
    <h1>Listagem de Vendas</h1>
    <table>
        <thead>
            <tr>
                <th>Vendedor</th>
                <th>Cliente</th>
                <th>Quantidade</th>
                <th>Valor da Venda</th>
                <th>Desconto</th>
                <th>Dia da Semana</th>
                <th>Data Entrega</th>
            </tr>
        </thead>
        <tbody>
            {% for venda in vendas %}
            <tr>
                <td>{{ venda.vendedor.nome }}</td>
                <td>{{ venda.cliente.nome }}</td>
                <td>{{ venda.quantidade }}</td>
                <td>{{ venda.calcular_valor }}</td>
                <td>{{ venda.tem_deconto }}</td>
                <td>{{ venda.dia_da_semana }}</td>
                <td>{{ venda.data_entrega }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

granja/templates/granja/pages/products.html
{% extends "granja/base.html" %}
{% load static %}

{% block main_container %}
<div class="pd-ltr-20 xs-pd-20-10">
    <div class="min-height-200px">
        {% with title="Produtos" %}
            {% include "granja/partials/sub-header.html" %}
        {% endwith %}
        <div class="product-wrap">
            <div class="product-list">
                <ul class="row">
                    {% for produto in produtos %}
                        <li class="col-lg-4 col-md-6 col-sm-12">
                            <div class="product-box">
                                <div class="producct-img">
                                    <img src="{{ produto.foto.url }}" alt="">
                                </div>
                                <div class="product-caption">
                                    <h4><a href="#">{{ produto.nome }}</a></h4>
                                    <div class="price"><del>R${{ produto.preco_riscado|floatformat:2 }}</del><ins>R${{ produto.preco|floatformat:2 }}</ins></div>
                                    <a href="#" class="btn btn-outline-primary">Comprar!</a>
                                    <a href="{% url 'granja:editar_produto' produto.id %}" class="btn btn-outline-info">Editar</a>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <!--
            <div class="blog-pagination mb-30">
                <div class="btn-toolbar justify-content-center mb-15">
                    <div class="btn-group">
                        <a href="#" class="btn btn-outline-primary prev"><i class="fa fa-angle-double-left"></i></a>
                        <a href="#" class="btn btn-outline-primary">1</a>
                        <a href="#" class="btn btn-outline-primary">2</a>
                        <span class="btn btn-primary current">3</span>
                        <a href="#" class="btn btn-outline-primary">4</a>
                        <a href="#" class="btn btn-outline-primary">5</a>
                        <a href="#" class="btn btn-outline-primary next"><i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
            -->
        </div>
    </div>
    <!--
    <div class="footer-wrap pd-20 mb-20 card-box">
        DeskApp - Bootstrap 4 Admin Template By
        <a href="https://github.com/dropways" target="_blank">Ankit Hingarajiya</a>
    </div>
    -->
</div>
{% endblock main_container %}

granja/templates/granja/pages/vendas.html
{% extends "granja/base.html" %}
{% load static %}

{% block main_container %}
<div class="pd-ltr-20 xs-pd-20-10">
    <div class="pd-20 card-box mb-30">
        <div class="clearfix mb-20">
            <div class="pull-left">
                <h4 class="text-blue h4">Vendas Ovos Seu João</h4>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="white-space: nowrap;" scope="col">Cliente</th>
                        <th style="white-space: nowrap;" scope="col">Produto</th>
                        <th style="white-space: nowrap;" scope="col">Quantidade</th>
                        <th style="white-space: nowrap;" scope="col">Valor da Venda</th>
                        <th style="white-space: nowrap;" scope="col">Desconto</th>
                        <th style="white-space: nowrap;" scope="col">Dia da Semana</th>
                        <th style="white-space: nowrap;" scope="col">Data de Entrega</th>
                        <th style="white-space: nowrap;" scope="col">Editar Venda</th>
                    </tr>
                </thead>
                <tbody>
                    {% for venda in vendas %}
                    <tr>
                        <td style="white-space: nowrap;">{{ venda.cliente.nome }}</td>
                        <td style="white-space: nowrap;">{{ venda.produto.nome }}</td>
                        <td style="white-space: nowrap;">{{ venda.quantidade }}</td>
                        <td style="white-space: nowrap;">R${{ venda.valor_total|floatformat:2 }}</td>
                        <td style="white-space: nowrap;">{{ venda.get_desconto }}</td>
                        <td style="white-space: nowrap;">{{ venda.dia_da_semana|title }}</td>
                        <td style="white-space: nowrap;">{{ venda.data_entrega }}</td>
                        <td>
                            <a href="{% url 'granja:editar_venda' venda.id %}" class="badge -secondary">Editar Venda</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
                                
        </div>
    </div>
</div>
{% endblock main_container %}