granja/urls.py
from django.urls import path
from granja import views

app_name = 'granja'

urlpatterns = [
    path('', views.vendas, name='index'), 
    path('dashboard/', views.dashboard, name='dashboard'), 

    path('empresa/<str:arroba>/', views.empresa),

    path('produtos/', views.produtos, name='produtos'),
    path('produto/criar/', views.criar_produto, name='criar_produto'),
    path('produto/<int:id>/editar/', views.editar_produto, name='editar_produto'),
    path('produto/<int:id>/excluir/', views.excluir_produto, name='excluir_produto'),  

    path('vendas/', views.vendas, name='vendas'),
    path('venda/criar/', views.gerar_venda, name='gerar_venda'),
    path('venda/<int:id>/editar/', views.editar_venda, name='editar_venda'),
    path('venda/<int:id>/excluir/', views.excluir_venda, name='excluir_venda'),
    path('excluir/<str:model>/<int:pk>/', views.excluir, name='excluir'),  

    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('', include('granja.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

granja/forms.py
from datetime import date
from django import forms
from .models import Produto, Venda, Cliente
from django.forms.widgets import TextInput, NumberInput, Select, FileInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'telefone', 'endereco', 'meio_de_contato']
        widgets = {
            'nome': TextInput(attrs={'class': 'form-control'}),
            'telefone': TextInput(attrs={'class': 'form-control'}),
            'endereco': TextInput(attrs={'class': 'form-control'}),
            'meio_de_contato': Select(attrs={'class': 'custom-select col-12'}),
        }

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
            'foto',
            'nome', 
            'preco_riscado', 
            'preco',
            'descricao',
            'estoque', 
            'arquivado',
            #'cor', 
        ]
        widgets = {
            'estoque': Select(attrs={
                'class': 'custom-select col-12'
            }),
            'nome': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ovos...'
            }),
            'preco_riscado': NumberInput(attrs={
                'class': 'form-control',
                'value': '20.00'
            }),
            'preco': NumberInput(attrs={
                'class': 'form-control',
                'value': '17.00'
            }),
            'cor': TextInput(attrs={
                'class': 'form-control',
                'value': '#563d7c',
                'type': 'color'
            }),
            'foto': FileInput(attrs={'class': 'form-control-file form-control height-auto'}),
            'descricao': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ovos Caipira...'
            }),
        }

class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = [
            #'vendedor',
            'cliente',
            'produto',
            'quantidade',
            'meio_de_pagamento',
            'desconto',
            #'data_pedido',
            'data_entrega',
        ]
        widgets = {
            'cliente': forms.Select(attrs={'class': 'custom-select col-12'}),
            'produto': forms.Select(attrs={'class': 'custom-select col-12'}),
            'quantidade': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': 1
            }),
            'meio_de_pagamento': forms.Select(attrs={'class': 'custom-select col-12'}),
            'desconto': forms.Select(attrs={'class': 'custom-select col-12'}),
            
            'data_entrega': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance and instance.data_entrega:
            self.initial['data_entrega'] = instance.data_entrega.strftime('%Y-%m-%d')
        if not self.instance.pk:  
            self.fields['data_entrega'].initial = date.today().isoformat()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

granja/views.py
from django.shortcuts import render, redirect, get_object_or_404
from granja.models import Venda, Produto, Estoque, Cliente, Vendedor, AppUser
from granja.forms import ProdutoForm, VendaForm, ClienteForm, UserRegisterForm
from .dashboard import Dashboard
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    return render(request, 'granja/pages/vendas.html', {
        'vendas': Venda.objects.all(),
    })


def dashboard(request):
    today = datetime.today()
    option = None

    if request.method == "GET":
        date_str = request.GET.get('date')
        option = request.GET.get('option')

        if date_str:
            today = datetime.strptime(date_str, '%d-%m-%Y')

    if option == '1':
        dashboard_obj = Dashboard(today)
    elif option == '2':
        last_week = today - timedelta(days=7)
        dashboard_obj = Dashboard(last_week)
    else:
        dashboard_obj = Dashboard(today)

    #today = datetime(2024, 6, 23)
    dashboard = Dashboard(today)

    semana_passada = dashboard.totais_semana_passada
    semana_atual = dashboard.totais_semana_atual
    tamanho_grafico = dashboard.calcular_tamanho_grafico()
    messagem_whatsapp =  dashboard.mensagem

    clientes = dashboard.total_clientes
    lucro = dashboard.total_valor
    formas = dashboard.total_formas
    clientes_semana_passada = dashboard.total_clientes_semana_passada
    lucro_semana_passada = dashboard.total_valor_semana_passada
    formas_semana_passada = dashboard.total_formas_semana_passada

    diferenca_lucro = abs(dashboard.total_valor - dashboard.total_valor_semana_passada)
    porcentagem_aumento = 0

    if lucro == 0 or lucro_semana_passada == 0:
        porcentagem_aumento = 0
    else:
        porcentagem_aumento = (diferenca_lucro / min(lucro_semana_passada, lucro)) * 100


    return render(request, 'granja/pages/dashboard.html', {
        'option': option,
        'clientes': clientes,
        'lucro': lucro,
        'formas': formas,

        'clientes_semana_passada': clientes_semana_passada,
        'lucro_semana_passada': lucro_semana_passada,
        'formas_semana_passada': formas_semana_passada,
        'diferenca_lucro': diferenca_lucro,

        'porcentagem_aumento': porcentagem_aumento,

        'messagem_whatsapp': messagem_whatsapp,

        'semana_atual': semana_atual,
        'semana_passada': semana_passada,
        'tamanho_grafico': tamanho_grafico,

        'DIA_DA_SEMANA_CHOICES': Venda.DIA_DA_SEMANA_CHOICES,
    })


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        data = request.POST
        if form.is_valid():
            role = data.get('role', None)
            user = form.save(commit=False) 
            user.save()
            AppUser.objects.create(user=user, user_type=role)
            #print(form.cleaned_data, data, role)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Conta criada para {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'granja/auth/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, 'Usuário ou senha inválidos')
        else:
            messages.error(request, 'Usuário ou senha inválidos')
    else:
        form = AuthenticationForm()
    return render(request, 'granja/auth/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(dashboard)


def empresa(request, arroba):
    return render(request, 'granja/auth/auth.html')




def produtos(request):
    produtos = Produto.objects.all()

    return render(request, 'granja/pages/products.html', {
        'produtos': produtos,
        'sub_title': 'Produtos'
    })


def criar_produto(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('granja:index')
    else:
        form = ProdutoForm()

    form.fields['estoque'].queryset = Estoque.objects.all()  
    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'sub_title': 'Criar Produto'
        })


def editar_produto(request, id):
    obj = Produto
    editar = [True, obj.__name__.lower(), id]
    produto = get_object_or_404(obj, pk=id)
    

    if request.method == 'POST':
        form = ProdutoForm(request.POST, request.FILES, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('granja:produtos') 
    else:
        form = ProdutoForm(instance=produto)

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'produto': produto,
        'editar': editar,
        'sub_title': 'Editar Produto'
    })


def excluir_produto(request, id):
    try:
        Produto.objects.get(id=id).delete()
    except Exception as e:
        print("Error!")
    return redirect('granja:produtos')


def vendas(request):
    vendas = Venda.objects.all().order_by('-data_entrega')[:20]

    return render(request, 'granja/pages/vendas.html', {
        'vendas': vendas,
        'sub_title': 'Vendas'
    })


def gerar_venda(request):
    if request.method == 'POST':
        form = VendaForm(request.POST, request.FILES)
        form2 = ClienteForm(request.POST, request.FILES)
        if form2.is_valid():
            cliente = form2.cleaned_data
            cliente['nome'] = cliente['nome'].title()
        
            obj = None
            meio_de_contato = cliente['meio_de_contato']            
            list_filter = {
                '1': Cliente.objects.check(nome=cliente['nome'], telefone=cliente['telefone'], meio_de_contato=meio_de_contato),
                '2': Cliente.objects.check(telefone=cliente['telefone'], meio_de_contato=meio_de_contato),
                '3': Cliente.objects.check(nome=cliente['nome'], meio_de_contato=meio_de_contato),
            }

            cliente_id = None
            for key, value in list_filter.items():
                if value:
                    cliente_id = value.id
                    break

            if cliente_id:
                obj = Cliente.objects.get(id=cliente_id)
            else:
                obj = Cliente.objects.create(**cliente)

            if not obj.nome and cliente.get('nome', None) is not None:
                obj.nome = cliente['nome']
            if not obj.nome and cliente.get('nome', None) is not None:
                obj.nome = cliente['nome']
            if not obj.endereco and cliente.get('endereco', None) is not None:
                obj.endereco = cliente['endereco']
            obj.save()

            if form.is_valid():
                venda = form.save(commit=False)
                venda.cliente = obj
                venda.save()
                return redirect('granja:index')        
    else:
        form = VendaForm()
        form2 = ClienteForm()

    #form.fields['cliente'].queryset = Cliente.objects.all()
    form.fields['produto'].queryset = Produto.objects.all()

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'form2': form2,
        'sub_title': 'Gerar Venda'
    })


def editar_venda(request, id):
    obj = Venda
    editar = [True, obj.__name__.lower(), id]
    venda = get_object_or_404(obj, pk=id)

    if request.method == 'POST':
        form = VendaForm(request.POST, request.FILES, instance=venda)
        if form.is_valid():
            form.save()
            return redirect('granja:vendas') 
    else:
        form = VendaForm(instance=venda)

    return render(request, 'granja/pages/admin_form.html', {
        'form': form,
        'venda': venda,
        'editar': editar,
        'sub_title': 'Editar Venda'
    })


def excluir_venda(request, id):
    try:
        Venda.objects.get(id=id).delete()
    except Exception as e:
        print("Error!")
    return redirect('granja:produtos')


def excluir(request, model, pk):
    url_anterior = request.META.get('HTTP_REFERER', '/')
    model_class = {
        'venda': Venda,
        'produto': Produto,
        'cliente': Cliente,
    }.get(model)

    if model_class is None:
        return redirect(url_anterior)

    objeto = get_object_or_404(model_class, pk=pk)
    
    objeto.delete()
    return redirect('granja:index')

granja/templates/granja/partials/header.html
{% load static %}
<div class="header">
    <div class="header-left">
        <div class="menu-icon bi bi-list"></div>
        <div class="search-toggle-icon bi bi-search" data-toggle="header_search"></div>
        <div class="header-search">
            <form>
                <div class="form-group mb-0">
                    <i class="dw dw-search2 search-icon"></i>
                    <input type="text" class="form-control search-input" placeholder="Search Here">
                    <div class="dropdown">
                        <a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
                            <i class="ion-arrow-down-c"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">From</label>
                                <div class="col-sm-12 col-md-10">
                                    <input class="form-control form-control-sm form-control-line" type="text">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">To</label>
                                <div class="col-sm-12 col-md-10">
                                    <input class="form-control form-control-sm form-control-line" type="text">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">Subject</label>
                                <div class="col-sm-12 col-md-10">
                                    <input class="form-control form-control-sm form-control-line" type="text">
                                </div>
                            </div>
                            <div class="text-right">
                                <button class="btn btn-primary">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="header-right">
        <div class="dashboard-setting user-notification">
            <div class="dropdown">
                <a class="dropdown-toggle no-arrow" href="javascript:;" data-toggle="right-sidebar">
                    <i class="dw dw-settings2"></i>
                </a>
            </div>
        </div>
        <div class="user-notification">
            <div class="dropdown">
                <a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
                    <i class="icon-copy dw dw-notification"></i>
                    <span class="badge notification-active"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="notification-list mx-h-350 customscroll mCustomScrollbar _mCS_1 mCS_no_scrollbar"><div id="mCSB_1" class="mCustomScrollBox mCS-dark-2 mCSB_vertical mCSB_inside" style="max-height: 0px;" tabindex="0"><div id="mCSB_1_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" style="position:relative; top:0; left:0;" dir="ltr">
                        <ul>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/img.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>John Doe</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/photo1.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>Lea R. Frith</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/photo2.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>Erik L. Richards</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/photo3.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>John Doe</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/photo4.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>Renee I. Hansen</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'granja/images/img.jpg' %}" alt="" class="mCS_img_loaded">
                                    <h3>Vicki M. Coleman</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipisicing
                                        elit, sed...
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div><div id="mCSB_1_scrollbar_vertical" class="mCSB_scrollTools mCSB_1_scrollbar mCS-dark-2 mCSB_scrollTools_vertical mCSB_scrollTools_onDrag_expand" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_1_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 30px; top: 0px;"><div class="mCSB_dragger_bar" style="line-height: 30px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div></div>
                </div>
            </div>
        </div>
        <div class="user-info-dropdown">
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                    <span class="user-icon">
                        <img src="{% static 'granja/images/photo1.jpg' %}" alt="">
                    </span>
                    <span class="user-name">Ovos Seu João</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                    <a class="dropdown-item" href="profile.html"><i class="dw dw-user1"></i> Profile</a>
                    <a class="dropdown-item" href="profile.html"><i class="dw dw-settings2"></i> Setting</a>
                    <a class="dropdown-item" href="faq.html"><i class="dw dw-help"></i> Help</a>
                    <a class="dropdown-item" href="login.html"><i class="dw dw-logout"></i> Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>

granja/templates/granja/partials/sidebar.html
{% load static %}

<div class="sidebar-light">
    <div class="left-side-bar">
        <div class="brand-logo">
            <a href="{% url 'granja:index' %}">
                <img src="{% static 'granja/images/deskapp-logo.svg' %}" alt="" class="dark-logo">
                <img src="{% static 'granja/images/deskapp-logo-white.svg' %}" alt="" class="light-logo">
            </a>
            <div class="close-sidebar" data-toggle="left-sidebar-close">
                <i class="ion-close-round"></i>
            </div>
        </div>
        <div class="menu-block customscroll">
            <div class="sidebar-menu">
                <ul id="accordion-menu">
                    <li>
                        <a href="{% url 'granja:dashboard' %}" class="dropdown-toggle no-arrow">
                            <span class="micon bi bi-clipboard-data"></span><span class="mtext">Dashboad</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-option="off">
                            
                            <span class="micon bi bi-bag-check-fill"></span><span class="mtext">Vendas</span>
                        </a>
                        <ul class="submenu">
                            <li >
                                <a href="{% url 'granja:gerar_venda' %}">Gerar Venda</a>
                            </li>
                            <li>
                                <a href="{% url 'granja:vendas' %}">Ver Vendas</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-option="off">
                            <span class="micon bi bi-shop"></span><span class="mtext">Produtos</span>
                        </a>
                        <ul class="submenu">
                            <li><a href="{% url 'granja:produtos' %}">Ver Produtos</a></li>
                            <li><a href="{% url 'granja:criar_produto' %}">Criar Produtos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-option="off">
                            <span class="micon bi bi-table"></span><span class="mtext">Tables</span>
                        </a>
                        <ul class="submenu">
                            <li><a href="basic-table.html">Basic Tables</a></li>
                            <li><a href="datatable.html">DataTables</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-option="off">
                            <span class="micon bi bi-box2-fill"></span><span class="mtext"> Estoque </span>
                        </a>
                        <ul class="submenu">
                            
                            <li><a href="#">Ovos</a></li>
                            <li><a href="#">Ração</a></li>
                        </ul>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <div class="sidebar-small-cap">Extra</div>
                    </li>
                    
                    <li>
                        <a href="https://dropways.github.io/deskapp-free-single-page-website-template/" target="_blank" class="dropdown-toggle no-arrow">
                            <span class="micon bi bi-layout-text-window-reverse"></span>
                            <span class="mtext">Landing Page
                                <img src="{% static 'granja/images/coming-soon.png' %}" alt="" width="25" class="mCS_img_loaded"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
        
</div>
<div class="mobile-menu-overlay"></div>

granja/templates/granja/partials/sub-header.html
<div class="page-header">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="title">
                <h4>{{ sub_title }}</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'granja:index' %}">Início</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {{ sub_title }}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>